# Generated by Django 4.2.5 on 2023-09-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Defualt Skill',
                'verbose_name_plural': 'Default Skills',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('percentage_attained', models.IntegerField(blank=True, null=True)),
                ('test', models.ManyToManyField(to='stats.test')),
            ],
            options={
                'verbose_name': 'Candidate Test',
                'verbose_name_plural': 'Candidate Tests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_candidate_user', models.BooleanField(default=False)),
                ('is_company_user', models.BooleanField(default=False)),
                ('is_prime', models.BooleanField(default=False)),
                ('disable_send', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_membership', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('token', models.CharField(blank=True, max_length=4096, null=True)),
                ('uid', models.CharField(blank=True, max_length=4096, null=True)),
                ('is_aragreement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='stats.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_training', to='users.user')),
            ],
            options={
                'verbose_name': 'Candidate Training',
                'verbose_name_plural': 'Candidate Training',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.questions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('user_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTest', to='users.test')),
            ],
            options={
                'verbose_name': 'Candidate Test Q&A',
                'verbose_name_plural': 'Candidate Test (Q&A)s',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_user_test', to='users.training'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='users.user')),
            ],
            options={
                'verbose_name': 'Candidate Resume',
                'verbose_name_plural': 'Candidate Resumes',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('currently_working', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField()),
                ('end_date', models.DateField()),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='users.user')),
            ],
            options={
                'verbose_name': 'Experience Details',
                'verbose_name_plural': 'Experience Details',
            },
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(choices=[('bachelors', 'BACHELORS'), ('masters', 'MASTERS'), ('doctorate', 'DOCTORATE'), ('diploma', 'DIPLOMA'), ('high_school', 'HIGH SCHOOL')], max_length=30)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.CharField(choices=[('MCA', 'MCA - Masters of Computer Application'), ('B.Sc.', 'B.Sc.- Information Technology'), ('BBA', 'BBA- Bachelor of Business Administration'), ('BMS', 'BMS- Bachelor of Management Science'), ('BFA', 'BFA- Bachelor of Fine Arts'), ('BEM', 'BEM- Bachelor of Event Management'), ('BFD', 'BFD- Bachelor of Fashion Designing'), ('A&B', 'Automation and Robotics'), ('B.Com', 'B.Com- Bachelor of Commerce')], max_length=30)),
                ('passing_out_year', models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013')], max_length=5)),
                ('education_type', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational', to='users.user')),
            ],
            options={
                'verbose_name': 'Educational Detail',
                'verbose_name_plural': 'Educational Details',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/certificate')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_certificate', to='users.training')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='users.skills')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='files')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='files')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_agreement', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.cities')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.countries')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.state')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.user')),
            ],
            options={
                'verbose_name': 'Address Detail',
                'verbose_name_plural': 'Address Details',
            },
        ),
        migrations.CreateModel(
            name='CandidateUser',
            fields=[
            ],
            options={
                'verbose_name': 'Candidate user',
                'verbose_name_plural': 'Candidate user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Trainingvideos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_training_videos', to='stats.coursevideos')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_videos', to='users.training')),
            ],
            options={
                'managed': True,
                'unique_together': {('training', 'episode')},
            },
        ),
    ]
